name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        ruby: ["3.4"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          fetch-tags: true
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install igraph (macOS)
        if: ${{ matrix.os == 'macos' }}
        run: |
          brew install igraph
      - name: Install igraph (Ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libxml2-dev libgmp-dev libblas-dev liblapack-dev libglpk-dev
          cd igraph
          mkdir -p build && cd build
          cmake .. -DBUILD_SHARED_LIBS=ON -DIGRAPH_ENABLE_LTO=ON -DIGRAPH_OPENMP_SUPPORT=ON -DIGRAPH_GRAPHML_SUPPORT=ON -DIGRAPH_GLPK_SUPPORT=ON -DIGRAPH_ENABLE_TLS=ON -DUSE_CCACHE=ON -DFORCE_COLORED_OUTPUT=ON
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Install igraph (Windows)
        if: ${{ matrix.os == 'windows' }}
        run: |
          ridk exec pacman -Syu --noconfirm
          ridk exec pacman -S --noconfirm mingw-w64-x86_64-igraph
      - name: Build and test with Rake
        run: |
          bundle exec rake
